### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by sudip550** [ARajgor/cp-vton-plus#4]
Namespace(name='GMM', gpu_ids='', workers=4, batch_size=4, dataroot='data', datamode='train', stage='GMM', data_list='train_pairs.txt', fine_width=192, fine_height=256, radius=5, grid_size=5, lr=0.0001, tensorboard_dir='tensorboard', checkpoint_dir='checkpoints', checkpoint='', display_count=20, save_count=5000, keep_step=100000, decay_step=100000, shuffle=True)
Start to train stage: GMM, named: GMM!
initialization method [normal]
initialization method [normal]
Traceback (most recent call last):
  File "C:\Users\Sudip\cp-vton-plus\train.py", line 232, in <module>
    main()
  File "C:\Users\Sudip\cp-vton-plus\train.py", line 210, in main
    model = GMM(opt)
  File "C:\Users\Sudip\cp-vton-plus\networks.py", line 512, in __init__
    self.regression = FeatureRegression(
  File "C:\Users\Sudip\cp-vton-plus\networks.py", line 129, in __init__
    self.conv.cuda()
  File "C:\Users\Sudip\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Sudip\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Sudip\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\Sudip\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Sudip\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ARajgor** [comment]
This Torch library error. you have to install a torch with Cuda. [Learn More](https://pytorch.org/get-started/locally/)
